### PR TITLE
Task00 Кудрявцев Федор HSE

### PR DESCRIPTION
**Pull request by koufesser**

### CODE REVIEW

**Comment by koufesser** [comment]
<details><summary>Локальный вывод</summary><p>

<pre>
C:\Users\koufe\GPGPUTasks2024\cmake-build-debug\enumDevices.exe
Number of OpenCL platforms: 1
Platform #1/1
    Platform name: Intel(R) OpenCL HD Graphics
    Platform vendor: Intel(R) Corporation
    Device name: Intel(R) Iris(R) Xe Graphics
    Device type: ♦
   Global mem size: 6712225792
    Local mem size: 6712225792
    Max clock frequency: 1500
</pre>
</p></details>


<details><summary>Вывод Github CI</summary><p>

<pre>
Run ./build/enumDevices
Number of OpenCL platforms: 1
Platform #1/1
    Platform name: Intel(R) CPU Runtime for OpenCL(TM) Applications
    Platform vendor: Intel(R) Corporation
    Device name: AMD EPYC 77[6](https://github.com/GPGPUCourse/GPGPUTasks2024/pull/112/checks#step:7:7)3 64-Core Processor                
    Device type: 
   Global mem size: 16[7](https://github.com/GPGPUCourse/GPGPUTasks2024/pull/112/checks#step:7:8)68327680
    Local mem size: 1676[8](https://github.com/GPGPUCourse/GPGPUTasks2024/pull/112/checks#step:7:9)327680
    Max clock frequency: 0
</pre>

</p></details>

**Comment by simiyutin** [comment]
Память лучше выводить хотя бы в мегабайтах, чтобы было проще воспринимать

**Comment by koufesser** [comment]
<details><summary>Локальный вывод</summary><p>

<pre>
C:\Users\koufe\GPGPUTasks2024\cmake-build-debug\enumDevices.exe
Number of OpenCL platforms: 2
Platform #1/2
Platform name is ok
    Platform name: Intel(R) OpenCL HD Graphics
    Platform vendor: Intel(R) Corporation
    Device name: Intel(R) Iris(R) Xe Graphics
    Device type: ♦
   Global mem size: 6401 Mb
    Local mem size: 0 Mb
    Max clock frequency: 1500
Platform #2/2
Platform name is ok
    Platform name: Intel(R) OpenCL
    Platform vendor: Intel(R) Corporation
    Device name: 13th Gen Intel(R) Core(TM) i7-13700H
    Device type: ☻
   Global mem size: 16003 Mb
    Local mem size: 0 Mb
    Max clock frequency: 0
</pre>
</p></details>


<details><summary>Вывод Github CI</summary><p>

<pre>
Run ./build/enumDevices
Number of OpenCL platforms: 1
Platform #1/1
Platform name is ok
    Platform name: Intel(R) CPU Runtime for OpenCL(TM) Applications
    Platform vendor: Intel(R) Corporation
    Device name: AMD EPYC 7763 64-Core Processor                
    Device type: 
   Global mem size: 15991 Mb
    Local mem size: 0 Mb
    Max clock frequency: 0
</pre>

</p></details>

**Comment by simiyutin** [comment]
Все хорошо, задача зачтена, 5/5 баллов :+1:

**Pull request closed without merging**
